### ISSUE TITLE
ciao-controller: Use FQDN instead of os.Hostname (hostname)

### ISSUE THREAD

**Issue by obedmr** [01org/ciao#1005]
Golang function ``os.Hostname()`` ([sample code](https://github.com/01org/ciao/blob/master/ciao-controller/main.go#L219)) is returning the hostname without domain name instead of the FQDN (Fully Qualified Domain Name). This can cause the following error:

```
E0110 22:39:23.957792    2145 main.go:235] ciao-cli ERROR: Could not send HTTP request Post https://my-hostname:8889/workloads: x509: certificate is valid for localhost, not my-hostname
F0110 22:39:23.958062    2145 workload.go:291] ciao-cli FATAL: Post https://my-hostname:8889/workloads: x509: certificate is valid for localhost, not my-hostname
goroutine 1 [running]:
github.com/01org/ciao/vendor/github.com/golang/glog.stacks(0x981400, 0xc400000000, 0xa4, 0x111)
        /root/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:769 +0xa5
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).output(0x9650a0, 0xc400000003, 0xc4202503c0, 0x9402d2,0xb, 0x123, 0x0)
        /root/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:720 +0x357
github.com/01org/ciao/vendor/github.com/golang/glog.(*loggingT).printDepth(0x9650a0, 0xc400000003, 0x1, 0xc4200ffb88, 0x1, 0x1)
        /root/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:646 +0x126
github.com/01org/ciao/vendor/github.com/golang/glog.FatalDepth(0x1, 0xc4200ffb88, 0x1, 0x1)
        /root/go/src/github.com/01org/ciao/vendor/github.com/golang/glog/glog.go:1134 +0x5d
main.fatalf(0xc420122e00, 0x64, 0x0, 0x0, 0x0)
        /root/go/src/github.com/01org/ciao/ciao-cli/main.go:132 +0x126
main.(*workloadCreateCommand).run(0xc420072e70, 0xc420074090, 0x0, 0x0, 0xc420074090, 0x0)
        /root/go/src/github.com/01org/ciao/ciao-cli/workload.go:291 +0x5b0
main.(*command).run(0x963510, 0xc420074090, 0x0, 0x0, 0xc4200b0cd8, 0x0)
        /root/go/src/github.com/01org/ciao/ciao-cli/main.go:58 +0x15b
main.main()
        /root/go/src/github.com/01org/ciao/ciao-cli/main.go:466 +0xf7
```

For this example, I tested with certificates that only supported ``localhost``as hostname

**Comment by obedmr** [comment]
@tpepper could you please comment with the proposal you were comenting in IRC?

**Comment by tpepper** [comment]
os.Hostname() clearly only returns the hostname even if the machine is correctly configured to with a FQDN, and is documented to do so.  There is no os.Domainname().

When we were chatting on IRC I came across: https://github.com/ShowMax/go-fqdn/blob/master/fqdn.go

It's really a shame golang doesn't abstract the OS variations and let you directly get the hostname.  I'm not crazy about the package at the url above as I don't think it's dependence on DNS (possibly external to the machine) will give consistent/correct answers depending on machine configuration.

It would be worth looking through the golang forums and bugs for discussion of the history of this topic and if there's a preferred way to deal with it.

I suspect we simply need to rely on explicit configuration rather than the library call.
