### ISSUE TITLE
Improve datastore unit testing by creating fake persistent datastores

### ISSUE THREAD

**Issue by kaccardi** [01org/ciao#403]
Change the way that the datastore unit tests are written to use a fake persistent datastores that can be instrumented to return success or failure. This will make it easier to test error paths in datastore.

**Comment by tpepper** [comment]
More detail:

Current controller test implementation uses sleeps for synchronization, because it uses the real controller datastore which does asynchronous writes to the sql backing store.  It is asynchronous by design.

For our tests though we want to know that a specific action has occurred before we carry on to a next action.  Since there's no synchronous success/failure return by design from the sql data store, the tests can't know today that a first action is done before a next.

Refactoring to a datastore interface means we can implement a fake datastore, instead of the sql one, for test purposes.  For its implementation we'd get either synchronous changes to data with function return meaning the data was definitely stored, or keep asynchronous return but add a channel by which the implementation can indicate to the asynchronous function caller that the work is done, or it would only serve pre-canned static data.  Then when a test sub-point B needs the data from test sub-point A, we know that data is present and B will deterministically be able to successfully run.

Then we can remove the sleeps from the controller test cases, and do some go-race checking also.
