### ISSUE TITLE
configuration: pass ceph cluster info

### ISSUE THREAD

**Issue by tpepper** [01org/ciao#462]
Modify the configuration payload topropagate the ceph cluster info, so that launcher can auto mount the /var/lib/ciao/images point if it is not already mounted.

**Comment by markdryan** [comment]
@bryteise is going to work on this,.

**Comment by markdryan** [comment]
The nice thing about this ticket is that you should be able to develop and test using only launcher and it's test tools.

Install launcher following the instructions [here](https://github.com/01org/ciao/blob/master/ciao-launcher/README.md).

For this ticket you need to work from the storage branch kaccardi/topic/storage.   So basically, you can do a 

go get -d github.com/01org/ciao/ciao-launcher
cd $GOPATH/src/github.com/01org/ciao/ciao-launcher
git checkout kaccardi/topic/storage
and then go build or go install

Once you've got it building, look further down the document for the section entitled 'Testing ciao-launcher in Isolation'.  Build the test tools and make sure you can send launcher commands via ciaolc.

Then it's time to code.  The problem we need to solve here is that we are hard coding two settings in [lines 403 and 404 of instance.go](https://github.com/01org/ciao/blob/kaccardi/topic/storage/ciao-launcher/instance.go#L403).  These values should come from the configuration data that launcher receives when it connects to the ssntp server.  Normally, this is scheduler, but to test and develop this feature we can use ciao-launcher-server as described in the readme above.

Launcher receives its configuration  information from the ssntp server in (main.go)[https://github.com/01org/ciao/blob/kaccardi/topic/storage/ciao-launcher/main.go#L380].  If you click on the link you'll see it currently retrieves the compute and management networks and disk and memory limits.  We need to add two new settings, key path and ceph id.

Off the top of my head, here are the steps

1. Add the new settings to the (configuration structure)[https://github.com/01org/ciao/blob/kaccardi/topic/storage/payloads/configure.go#L84] and make sure you update configure_test.go as well.
2. Add two new command line parameters to ciao-launcher-server for the keypath and the management id.  These will allow you to specify different values when testing.  The values you pass into the command line of ciao-launcher-server should make it to launcher.
3. Modify main.go in launcher to receive the new settings.  It's safe to store them in global variables in a similar way to the other settings.
4. Modify instance.go to use the global variables instead of the hardcoded values.
5. Update the test cases in configuration/congfiuration_test.go to include your new settings.
6. Update configuration/README.md

@obedmr, @mrkz can you think of anything I've missed here?

**Comment by tpepper** [comment]
I missed it last week when I opened this ticket, but FYI https://github.com/01org/ciao/issues/388 is meant to cover this topic plus a bit more.

**Comment by markdryan** [comment]
I guess this ticket covers the last item

Add security secrets for cephx

At least for launcher.  Should controller also get its cephx info in the same way?  I guess it should.  Right now I think it's getting it from the command line.  So updating the controller configuration could be the next step.

**Comment by tpepper** [comment]
The ceph cluster and access secrets will need to be known by all nodes given our thinking that it's really handy to have /var/lib/ciao as the cephfs mount point shared by all nodes.  That would put both of those data points in the config info propagated by the server.

**Comment by markdryan** [comment]
Agreed.  Well let's start with launcher as we've already got the instructions.   Then I guess controller.  Does anything else need ceph?

**Comment by tpepper** [comment]
If we put logs centrally on the clustered storage, then scheduler would too.  But it doesn't technically/functionally need anything, where controller and launcher will.

**Comment by markdryan** [comment]
@tpepper So can we close this one now?  I think log handling for ceph stored logs should be handle by a separate ticket.

**Comment by tpepper** [comment]
Ticket covering logging abstraction across ciao and logs on ceph: https://github.com/01org/ciao/issues/512
