### ISSUE TITLE
osprepare: installs wrong package in ubuntu

### ISSUE THREAD

**Issue by albertomurillo** [01org/ciao#508]
Compute node requiremets in ubuntu includes 'docker' which is a KDE package.
the container runtime package is called 'docker.io'

**Comment by markdryan** [comment]
I made some comments on the PR but basically we shouldn't be installing docker-io.  We should be installing docker-engine.  We can only install this if the apt sources are correctly configured.  There seems to be some code in os-prepare to do this but it doesn't seem to be ready.

We also need to handle the case when docker is already installed from the Ubuntu repos.  We can't have two dockers.  What should we do here?  Remove docker-io first?

**Comment by tpepper** [comment]
I do think in principle this patch here is correct.  We want docker.io when on Ubuntu.

Separately we need a way to note that Ubuntu (or any distro) provides a docker (or any dep) not up to our minimum requirement and in that case consume from a distro-external / upstream content stream.  I'm looking at polishing of Ikey's code for this.

**Comment by tpepper** [comment]
I've confirmed the dockerproject.org deb's and rpm's internally note that they're "docker-engine" and they conflict with various typical distro package names, so that will block installation or updating to the desired docker.io if the distro's package is installed.  This is unfortunate as it's something we must conditionally handle, removing an existing one and replacing it.

**Comment by tpepper** [comment]
Given https://github.com/01org/ciao/issues/508#issuecomment-245441165 I propose it's easier and sufficient in the short term to ask for a simple clean system, add dockerproject.org repo, and set deps.go to say docker-engine instead of docker.io is the requisite.  That precludes us from using just a distro version, but so far the distro versions have always been hopelessly out of date.  We may never get around to being able to use anything but dockerproject.org's implementation.

**Comment by markdryan** [comment]
Okay, sounds good. Should the user forget to set up the sources we will get some warnings in the logs  guess.
