### ISSUE TITLE
osprepare: Fail to install bundles in clearlinux behind a proxy

### ISSUE THREAD

**Issue by albertomurillo** [01org/ciao#511]
osprepare is ran by the launcher to detect if there is a missing pacakge (qemu, docker, xorriso, etc)
and install the required bundle (cloud-control).

This task fails when running behind a proxy.

This is not an issue in ubuntu and fedora because you can configure the proxies in /etc/apt/apt.conf or /etc/dnf/dnf.conf

**Comment by tpepper** [comment]
Since osprepare has code for ClearLinux, Fedora and Ubuntu, and you say the latter two are ok, this sounds like it is a ClearLinux specific issue.  I thought ClearLinux has autoproxy, or a way to configure proxies manually for a system so system software can access a network?

I'm not sure how much osprepare itself can do about this.

**Comment by albertomurillo** [comment]
sudoFormatCommand() is not honoring environment variables from /etc/profile
making osprepare use env vars rom /etc/profile can fix the issue in clearlinux.

**Comment by tpepper** [comment]
I've got a patch which I think does the right thing, but need to test.

**Comment by tpepper** [comment]
Upon further code inspection withing golang, we're pretty sure this patch is actually unneeded.  It makes explicit grabbing the current Env, but if none was given (the state before the patch), the golang runtime pulls in the current Env.

I can only guess that the env was actually wrong (eg: maybe sudo didn't pass the user proxied env through to the root env running the ciao binary?)...in which case this bug is invalid?  But I'm guessing and assuming a lot here.  @albertomurillo if you can confirm how you're running things in more detail, eg: where is the proxy env var specified, what's the ciao command line and sudo arg's, etc., we can figure out more concretely what's gone wrong.

**Comment by albertomurillo** [comment]
I think this bug is invalid too.

The reason ciao-launcher is not getting the proxy env variables is because we are not starting ciao-launcher from the command line but from a systemd unit file.

I found that the admin can create /etc/systemd/system/ciao-compute.service.d/proxy.conf file
(docker style) to make ciao-launcher start with proxy environment values.

**Comment by tpepper** [comment]
Based on the last two comments I'm closing this as invalid, worked around in systemd standard way.
