### ISSUE TITLE
Ciao is using a deprecated --image-format

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#528]
The ceph storage driver currently specifies the "--image-format", "1" option when creating new ceph volumes.  The reason it does this is that we have problems mapping rbd images that used image-format 2 on some of our Ubuntu dev machines.  image-format 1 is deprecated so we should move back to image-format 2.

Changing to image-format 2 may require us to make some manual modifications to any ceph clusters running Ubuntu.

**Comment by albertomurillo** [comment]
as read in ceph documentation:

format 2 - Use the second rbd format, which is supported by librbd and kernel since version 3.11 (except for striping). This adds support for cloning and is more easily extensible to allow more features in the future.

We can use fimage format 2 and specify which --image-feature to use leaving out the ones not supported by the kernel client.
