### ISSUE TITLE
No way to boot from an existing volume without copying

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#759]
I think we're missing a use case (pet based) where you want to boot an instance from a volume without copying the volume. 

he current boot from volume code **always** copies the volume. I think this is wrong, if you boot from volume it should use that volume and not boot from a copy.

**Comment by rbradford** [comment]
@kaccardi Did I misunderstand something from the current design?

**Comment by kaccardi** [comment]
@rbradford it is supposed to work for existing volumes as well without a copy, if it doesn't, then it's a bug - which is highly likely since I never got around to testing this scenario. If you look in ciao-controller/instance.go/getStorage you should see a block of code like this:  

       // storage already exists, use preexisting definition.
        if s.ID != "" {
                return payloads.StorageResources{ID: s.ID, Bootable: s.Bootable}, nil
        }

This was supposed to cover the case when the storage was predefined and you just wanted to boot from it. Start there to see why it's not actually working.

**Comment by tpepper** [comment]
s.ID != "" means wl.Storage.ID != "", which I think would mean there needs to be a list of fields in the workload .csv for the optional boot volume for instance of that workload.  Or a single field, in which case only one instance of the workload is allowed.  That latter makes more sense, as otherwise we'd be turning the workload .csv into a instances csv.  But we may also need some instance specific persistent information.

**Comment by kaccardi** [comment]
@tpepper I think I'm not understanding your comment, but the storage definitions are contained in the workload_storage.csv file (and workload_storage sql table). The primary key for that table is a pair of workload_id and volume_id so it is possible to have multiple volumes per workload. but yes, the way it is now because we don't support having multiple instances booting from a single volume, it'd be a workload that the user would use for a pet.

**Comment by rbradford** [comment]
The original basis for this issue has been clarified. It is possible to boot an instance with an existing volume.
