### ISSUE TITLE
Ansible needs to upload image files

### ISSUE THREAD

**Issue by rbradford** [01org/ciao#841]
The ansible scripts need to upload the images that are used in the workload templates via "ciao-cli image new".

This is required as part of moving the images from the filesystem to ceph: #811

**Comment by rbradford** [comment]
The relevant steps to upload the images needed for the reference workloads can be found in in: https://github.com/01org/ciao/blob/master/testutil/singlevm/setup.sh#L300

**Comment by albertomurillo** [comment]
cnci image has to be converted to qcow before uploading to ciao-iamge

**Comment by rbradford** [comment]
SingleVM doesn't do any conversion of the image. Why do you think you need to do this in the ansible scripts?

**Comment by albertomurillo** [comment]
@rbradford it does at https://github.com/01org/ciao/blob/master/testutil/singlevm/setup.sh#L215
`qemu-img convert -f raw -O qcow2 "$ciao_cnci_image" "$ciao_cnci_image".qcow
`

**Comment by rbradford** [comment]
Ah okay. Have you tried uploading without converting? It's the image service will do the reverse operation as part of the upload so we can probably save time by not doing it!

**Comment by albertomurillo** [comment]
I can use os_image anisble module to upload the images to ciao-image since ciao-image is glance API compatible. This module however does not provides a way to specify the ID of the image and let's the API calculate one at creation time.

I believe is time that the image API stores the generated ID in the corresponding datastore rather than rely on the hardcoded IDs from workload_storage.csv
