### ISSUE TITLE
Attaching a volume to a stopped instance creates a zombie

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#872]
Check out the following steps:

```
$ ciao-cli volume add -name zombie -size 1
Created new volume: 0ee6471f-0f68-4875-bce6-acade1c6771c

$ ciao-cli instance list
# UUID                                 Status Private IP SSH IP        SSH PORT
1 4c573b13-26b7-4f82-beea-1d2380c36709 active 172.16.0.2 198.51.100.82 33002
2 7181b76b-5c60-40b6-8272-73b4197067aa active 172.16.0.3 198.51.100.82 33003
3 94131758-7485-44c4-b883-d6a9f9ab2ea9 active 172.16.0.4 198.51.100.82 33004
4 4d980203-299f-460d-9905-262ac9c7ccf2 exited 172.16.0.5 198.51.100.82 33005

$ ciao-cli volume attach --instance 4d980203-299f-460d-9905-262ac9c7ccf2 --volume 0ee6471f-0f68-4875-bce6-acade1c6771c
Attached volume: 0ee6471f-0f68-4875-bce6-acade1c6771c

$ sleep 60

$ ciao-cli volume show --volume  0ee6471f-0f68-4875-bce6-acade1c6771c
	Name             [zombie]
	Size             [1 GB]
	UUID             [0ee6471f-0f68-4875-bce6-acade1c6771c]
	Status           [attaching]
```

**Comment by kaccardi** [comment]
@markdryan I debugged this issue - the reason the status never updates to "in-use" here is because the instance stats for the exited instance only show the old attachments and are not updated to show the attachment that was added while the instance was exited. State change on volume attach relies completely on the stats since there is no "attached" event. If you had restarted the stopped instance, you would have seen the state change as the updated stats came in. So - this is either operator error in that you need to explicitly restart the instance before you can expect to show the attachment as fully attached (i.e. "in-use"), or you need to change launcher to send the stats with the updated attachment list.

**Comment by kaccardi** [comment]
needs a retest with the change in #886

**Comment by markdryan** [comment]
Agreed.   This is a launcher issue.  I've submitted a PR #887.   I've tested this PR in conjunction with #886 and the other PR submitted to fix the storage BAT tests.  All the tests pass.
