### ISSUE TITLE
ciao-cli,ciao-image: image in queued state if file does not exist

### ISSUE THREAD

**Issue by erick0z** [01org/ciao#874]
When creating an image via ciao-cli, if image does not exists, it throws a FATAL error and creates an empty image with a "queued" state.  The image register can't be deleted.

**Comment by markdryan** [comment]
@erick0z Could you specify the exact sequence of commands you used to generate this error?  When you say the image does not exist, do you mean that the image id does not currently exist in the image service or an invalid path is specified when trying to add a new image?

**Comment by erick0z** [comment]
Yes, with an invalid image path. The image is actually created in the ciao-image service with a queued state. The command is: ```ciao-cli image create -name test -file /invalid/image/path```.

**Comment by obedmr** [comment]
@erick0z according to the Image statuses we're following: http://developer.openstack.org/api-ref/image/v2/index.html#images, this is a valid status. Image is created in metadata store and it will return a cli error, because an invalid path. This issue is more in the ``ciao-cli``, it should validate that path is valid.

**Comment by erick0z** [comment]
@obedmr right!, I'll submit a fix to the cli.

**Comment by markdryan** [comment]
But we should never get into a situation where an image cannot be deleted.  If it is truly possible to create an image that cannot be deleted via the cli or the REST APIs then this is a problem in the image service as well.
