### ISSUE TITLE
Ciao has no control over the CNCI lifecycle

### ISSUE THREAD

**Issue by erick0z** [01org/ciao#912]
Right now, Ciao has no control over the CNCI other than spawning it. The CNCI runs forever since the first VM is launched. It would be good to shut down the CNCI if there is no VMs running and the state of the tenant is set to idle after "x" time.

**Comment by tpepper** [comment]
Part of the lifecycle management is also defining what is the cnci (initial base image), and maintaining that over time (new base image, restart cnci).  With the .csv workload definitions, today I think you'd need to edit the csv file, kill the cnci, restart controller and trigger a cnci relaunch somehow, in order to use a new cnci image.  It would be better if these were handled like any other system workload.

**Comment by rbradford** [comment]
Fixed by #1404
